Host/Controllers/Admin/ClientGrantTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lshp.OpenIDConnect.Service.AdminService;
using Lshp.OpenIDConnect.FilterAttributes;
using Microsoft.AspNetCore.Authorization;
using Lshp.OpenIDConnect.Service.AdminService.ClientViewModels;

namespace Lshp.OpenIDConnect.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    [SecurityHeaders]
    public class ClientGrantTypeController : Controller
    {
        public IManageOpenIDClient manageOpenIDClient;
        public ClientGrantTypeController(IManageOpenIDClient manageOpenIDClient)
        {
            this.manageOpenIDClient = manageOpenIDClient;
        }

        public async Task<IActionResult> GetClientGrantType(int id)
        {
            ViewBag.clientID = id;            
            return PartialView("ListAllowedGrantTypes", await manageOpenIDClient.FindClientGrantTypeByClientIdAsync(id));
        }

        public IActionResult Create(int clientID)
        {
            //var id = await manageOpenIDClient.GetIdByClientID(clientID);
            return View("_AddOrEdit", new ClientGrantType() { ClientId = clientID}); 
        }

        public async Task<IActionResult> EditClientGrantType(int id,int clientId)
        { 
            return View("_AddOrEdit", await manageOpenIDClient.FindClientGrantTypeByIdAsync(id, clientId));
        }

        [HttpPost]
        public async Task<IActionResult> EditClientGrantType(ClientGrantType client)
        { 
            if (ModelState.IsValid)
            {
                await manageOpenIDClient.StoreClientGrantType(client); 
                return RedirectToAction("GetClientGrantType", new { id = client.ClientId });
            }
            return View("_AddOrEdit", client);
        }
         
        public async Task<IActionResult> DeleteClientGrantType(int id,int clientId)
        {
            await manageOpenIDClient.RemoveClientGrantType(id, clientId);
            return RedirectToAction("GetClientGrantType", new { id = clientId });
        } 

        public IActionResult ClientGrantType()
        {
            return View();
        }
    }
}

Host/Views/ClientGrantType/ListAllowedGrantTypes.cshtml
@model IEnumerable<Lshp.OpenIDConnect.Service.AdminService.ClientViewModels.ClientGrantType>
@{ 
    Layout = null;
    var id = @ViewBag.clientID;
}

<a href="javascript:void(0)" data-newtarget="AddCustomGrantTypes_new" id="AddCustomGrantTypes" data-href="/ClientGrantType/Create?clientId=@id" class="singleajax">Add</a>
 <div id="AddCustomGrantTypes_new"></div>
<table class="table table-bordered table-hover">
    @foreach (var item in Model)
    {
        <tr><td><a href="javascript:void(0)" data-newtarget="AddCustomGrantTypes_new" id="deleteAddCustomGrantTypes_new" data-href="/ClientGrantType/DeleteClientGrantType/@item.Id?clientId=@item.ClientId" class="singleajax"><i class="fa fa-times" aria-hidden="true"></i></a></td> <td>@item.GrantType </td></tr>
    }
</table>
 
@Html.Partial("_ViewCommonJavascript")

Host/Views/ClientGrantType/_AddOrEdit.cshtml
@model Lshp.OpenIDConnect.Service.AdminService.ClientViewModels.ClientGrantType

@{ 
    Layout = null;
    var grantTypes = new List<SelectListItem>();


    grantTypes.Add(new SelectListItem() { Value = IdentityServer4.Models.GrantType.ClientCredentials, Text = IdentityServer4.Models.GrantType.ClientCredentials });
    grantTypes.Add(new SelectListItem() { Value = IdentityServer4.Models.GrantType.AuthorizationCode, Text = IdentityServer4.Models.GrantType.AuthorizationCode });
    grantTypes.Add(new SelectListItem() { Value = IdentityServer4.Models.GrantType.Hybrid, Text = IdentityServer4.Models.GrantType.Hybrid });
    grantTypes.Add(new SelectListItem() { Value = IdentityServer4.Models.GrantType.Implicit, Text = IdentityServer4.Models.GrantType.Implicit });
    grantTypes.Add(new SelectListItem() { Value = IdentityServer4.Models.GrantType.ResourceOwnerPassword, Text = IdentityServer4.Models.GrantType.ResourceOwnerPassword });

}
<form asp-controller="ClientGrantType" asp-action="EditClientGrantType" method="post" class="form-horizontal">
    @Html.Partial("_ValidationSummary")
    @Html.HiddenFor(i=>i.Id)
    @Html.HiddenFor(i => i.ClientId)
    @Html.DropDownListFor(i => i.GrantType, grantTypes)
    <button type="submit" class="btn btn-success">Add</button>
</form>

@Html.Partial("_ViewCommonJavascript")