Host/Controllers/Admin/ClientRedirectUriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lshp.OpenIDConnect.Service.AdminService;
using Lshp.OpenIDConnect.FilterAttributes;
using Microsoft.AspNetCore.Authorization;
using Lshp.OpenIDConnect.Service.AdminService.ClientViewModels;

namespace Lshp.OpenIDConnect.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    [SecurityHeaders]
    public class ClientRedirectUriController : Controller
    {
        public IManageOpenIDClient manageOpenIDClient;
        public ClientRedirectUriController(IManageOpenIDClient manageOpenIDClient)
        {
            this.manageOpenIDClient = manageOpenIDClient;
        }

        public async Task<IActionResult> GetClientRedirectUri(int id)
        {
            ViewBag.clientID = id;
            return PartialView("ListClientRedirectUri", await manageOpenIDClient.FindClientRedirectUriByClientIdAsync(id));
        }

        public  IActionResult Create(int clientId)
        {
            return View("_AddOrEdit", new ClientRedirectUri() {  ClientId  = clientId});
        }

        public async Task<IActionResult> EditClientRedirectUri(int id,int clientId)
        {
            return View("_AddOrEdit", await manageOpenIDClient.FindClientRedirectUriByIdAsync(id,clientId));
        }
        [HttpPost]
        public async Task<IActionResult> EditClientRedirectUri(ClientRedirectUri clientRedirectUri)
        {
            if (ModelState.IsValid)
            {
                await manageOpenIDClient.StoreClientRedirectUri(clientRedirectUri);
                return RedirectToAction("GetClientRedirectUri", new { id = clientRedirectUri.ClientId });
            }
            return View("_AddOrEdit", clientRedirectUri);
        }
         
        public async Task<IActionResult> DeleteClientRedirectUri(int id,int clientId)
        {
            await manageOpenIDClient.RemoveClientRedirectUri(id, clientId);
            return RedirectToAction("GetClientRedirectUri", new { id = clientId });
        } 

        public IActionResult ClientRedirectUri()
        {
            return View();
        }
    }
}

Host/Views/ClientRedirectUri/ListClientRedirectUri.cshtml
@model IEnumerable<Lshp.OpenIDConnect.Service.AdminService.ClientViewModels.ClientRedirectUri>
@{
    Layout = null;
    var id = @ViewBag.clientID;
}
<a href="javascript:void(0)" data-newtarget="AddClientRedirectUri_new" id="AddClientRedirectUri" data-href="/ClientRedirectUri/Create?clientId=@id" class="singleajax">Add</a>
<div id="AddClientRedirectUri_new"></div> 
<table class="table table-bordered table-hover">
    @foreach (var item in Model)
    {
        <tr><td><a href="javascript:void(0)" data-newtarget="AddClientRedirectUri_new" id="delClientRedirectUri_new" data-href="/ClientRedirectUri/DeleteClientRedirectUri/@item.Id?clientId=@item.ClientId" class="singleajax"><i class="fa fa-times" aria-hidden="true"></i></a></td> <td>@item.RedirectUri </td> </tr>
    }
</table>
 
@Html.Partial("_ViewCommonJavascript")

Host/Views/ClientRedirectUri/_AddOrEdit.cshtml
@model Lshp.OpenIDConnect.Service.AdminService.ClientViewModels.ClientRedirectUri

@{ 
    Layout = null;
}
<form asp-controller="ClientRedirectUri" asp-action="EditClientRedirectUri" method="post" class="form-horizontal">
    @Html.Partial("_ValidationSummary")
    @Html.HiddenFor(i=>i.Id)
    @Html.HiddenFor(i => i.ClientId)
    @Html.TextBoxFor(i => i.RedirectUri)
    <button type="submit" class="btn btn-success">Add</button>
</form>

@Html.Partial("_ViewCommonJavascript")