Host/Controllers/Admin/ClientSecretController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lshp.OpenIDConnect.Service.AdminService;
using Lshp.OpenIDConnect.FilterAttributes;
using Microsoft.AspNetCore.Authorization;
using Lshp.OpenIDConnect.Service.AdminService.ClientViewModels;
using IdentityServer4.Models;

namespace Lshp.OpenIDConnect.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    [SecurityHeaders]
    public class ClientSecretController : Controller
    {
        public IManageOpenIDClient manageOpenIDClient;
        public ClientSecretController(IManageOpenIDClient manageOpenIDClient)
        {
            this.manageOpenIDClient = manageOpenIDClient;
        }

        public async Task<IActionResult> GetClientSecret(int id)
        { 
            ViewBag.clientID = id;
            return PartialView("ListClientSecret",await manageOpenIDClient.FindClientSecretByClientIdAsync(id));
        }

        public  IActionResult Create(int clientid)
        {
            return View("_AddOrEdit", new ClientSecret() { ClientId=clientid });
        }

        public async Task<IActionResult> EditClientSecret(int id)
        {
            return View("_AddOrEdit", await manageOpenIDClient.FindClientSecretByClientIdAsync(id));
        }
        [HttpPost]
        public async Task<IActionResult> EditClientSecret(ClientSecret clientSecret)
        {
            if (ModelState.IsValid)
            {
                if(clientSecret.Type == IdentityServer4.IdentityServerConstants.SecretTypes.SharedSecret)
                {
                    clientSecret.Value = clientSecret.Value.Sha256();
                }

                await manageOpenIDClient.StoreClientSecret(clientSecret); 
                return RedirectToAction("GetClientSecret", new { id = clientSecret.ClientId });
            }
            return View("_AddOrEdit",clientSecret);
        }
         
        public async Task<IActionResult> DeleteClientSecret(int id,int clientId)
        {
            await manageOpenIDClient.RemoveClientSecret(id,clientId);
            return RedirectToAction("GetClientSecret", new { id = clientId });
        }
         
    }
}

Host/Views/ClientSecret/ListClientSecret.cshtml
@model IEnumerable<Lshp.OpenIDConnect.Service.AdminService.ClientViewModels.ClientSecret>
@{
    Layout = null;
    var id = @ViewBag.clientID;
}
<a href="javascript:void(0)" data-newtarget="AddClientSecret_new" id="AddClientSecret" data-href="/ClientSecret/Create?clientId=@id" class="singleajax">Add</a>
<div id="AddClientSecret_new"></div>
<table class="table table-bordered table-hover">
    <thead><tr><th></th><th>ID</th><th>Type</th><th>Value</th></tr> </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr><td><a href="javascript:void(0)" data-newtarget="AddClientSecret_new" id="DelClientSecret_new" data-href="/ClientSecret/DeleteClientSecret/@item.Id?clientId=@item.ClientId" class="singleajax"><i class="fa fa-times" aria-hidden="true"></i></a></td> <td>@item.Id</td><td>@item.Type</td><td>@item.Value</td></tr>
        }
    </tbody>
</table>

@Html.Partial("_ViewCommonJavascript")

Host/Views/ClientSecret/_AddOrEdit.cshtml
@model Lshp.OpenIDConnect.Service.AdminService.ClientViewModels.ClientSecret

@{ 
    Layout = null;
    var types = new List<SelectListItem>();

    types.Add( new SelectListItem() { Text = IdentityServer4.IdentityServerConstants.SecretTypes.SharedSecret, Value = IdentityServer4.IdentityServerConstants.SecretTypes.SharedSecret });
    types.Add(new SelectListItem() { Text = IdentityServer4.IdentityServerConstants.SecretTypes.X509CertificateBase64, Value = IdentityServer4.IdentityServerConstants.SecretTypes.X509CertificateBase64 });
    types.Add(new SelectListItem() { Text = IdentityServer4.IdentityServerConstants.SecretTypes.X509CertificateName, Value = IdentityServer4.IdentityServerConstants.SecretTypes.X509CertificateName });
    types.Add(new SelectListItem() { Text = IdentityServer4.IdentityServerConstants.SecretTypes.X509CertificateThumbprint, Value = IdentityServer4.IdentityServerConstants.SecretTypes.X509CertificateThumbprint });   
}
<form asp-controller="ClientSecret" asp-action="EditClientSecret" method="post" class="form-horizontal">
    @Html.Partial("_ValidationSummary")
    @Html.HiddenFor(i=>i.Id)
    @Html.HiddenFor(i => i.ClientId)
    @Html.DisplayFor(i=>i.Type)
    @Html.DropDownListFor(i => i.Type,types)
    @Html.DisplayFor(i => i.Value)
    @Html.TextBoxFor(i=>i.Value)
    @Html.DisplayFor(i => i.Description)
    @Html.TextBoxFor(i=>i.Description) 
    <button type="submit" class="btn btn-success">Add</button>
</form>

@Html.Partial("_ViewCommonJavascript")