Host/Controllers/Admin/ClientLogoutRedirectUriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lshp.OpenIDConnect.Service.AdminService;
using Lshp.OpenIDConnect.FilterAttributes;
using Microsoft.AspNetCore.Authorization;
using Lshp.OpenIDConnect.Service.AdminService.ClientViewModels;

namespace Lshp.OpenIDConnect.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    [SecurityHeaders]
    public class ClientLogoutRedirectUriController : Controller
    {
        public IManageOpenIDClient manageOpenIDClient;
        public ClientLogoutRedirectUriController(IManageOpenIDClient manageOpenIDClient)
        {
            this.manageOpenIDClient = manageOpenIDClient;
        }

        public async Task<IActionResult> GetClientLogoutRedirectUri(int id)
        {
            ViewBag.clientID = id;
            return PartialView("ListClientRedirectUri", await manageOpenIDClient.FindClientPostLogoutRedirectUriByClientIdAsync(id));
        }

        public  IActionResult Create(int clientId)
        {
            return View("_AddOrEdit", new ClientPostLogoutRedirectUri() {  ClientId  = clientId});
        }
         
        [HttpPost]
        public async Task<IActionResult> EditClientLogoutRedirectUri(ClientPostLogoutRedirectUri clientRedirectUri)
        {
            if (ModelState.IsValid)
            {
                await manageOpenIDClient.StoreClientPostLogoutRedirectUri(clientRedirectUri);
                return RedirectToAction("GetClientLogoutRedirectUri", new { id = clientRedirectUri.ClientId });
            }
            return View("_AddOrEdit", clientRedirectUri);
        }
         
        public async Task<IActionResult> DeleteClientLogoutRedirectUri(int id,int clientId)
        {
            await manageOpenIDClient.RemoveClientPostLogoutRedirectUri(id, clientId);
            return RedirectToAction("GetClientLogoutRedirectUri", new { id = clientId });
        } 

        public IActionResult ClientRedirectUri()
        {
            return View();
        }
    }
}

Host/Views/ClientLogoutRedirectUri/ListClientRedirectUri.cshtml
@model IEnumerable<Lshp.OpenIDConnect.Service.AdminService.ClientViewModels.ClientPostLogoutRedirectUri>
@{
    Layout = null;
    var id = @ViewBag.clientID;
}
<a href="javascript:void(0)" data-newtarget="AddClientPostRedirectUri_new" id="AddClientPostRedirectUri" data-href="/ClientLogoutRedirectUri/Create?clientId=@id" class="singleajax">Add</a>
<div id="AddClientPostRedirectUri_new"></div> 
<table class="table table-bordered table-hover">
    @foreach (var item in Model)
    {
        <tr><td><a href="javascript:void(0)" data-newtarget="AddClientPostRedirectUri_new" id="delClientPostRedirectUri_new" data-href="/ClientLogoutRedirectUri/DeleteClientLogoutRedirectUri/@item.Id?clientId=@item.ClientId" class="singleajax"><i class="fa fa-times" aria-hidden="true"></i></a></td> <td>@item.PostLogoutRedirectUri </td> </tr>
    }
</table>
 
@Html.Partial("_ViewCommonJavascript")

Host/Views/ClientLogoutRedirectUri/_AddOrEdit.cshtml
@model Lshp.OpenIDConnect.Service.AdminService.ClientViewModels.ClientPostLogoutRedirectUri

@{ 
    Layout = null;
}
<form asp-controller="ClientLogoutRedirectUri" asp-action="EditClientLogoutRedirectUri" method="post" class="form-horizontal">
    @Html.Partial("_ValidationSummary")
    @Html.HiddenFor(i=>i.Id)
    @Html.HiddenFor(i => i.ClientId)
    @Html.TextBoxFor(i => i.PostLogoutRedirectUri)
    <button type="submit" class="btn btn-success">Add</button>
</form>

@Html.Partial("_ViewCommonJavascript")